## Setups

In [2]:
import pandas as pd

In [1]:
import requests
import pandas as pd

def get_coordinates(address, api_key):
    """
    Fetches latitude and longitude for a given address using Google Geocoding API.

    :param address: Address to geocode.
    :param api_key: Google API key.
    :return: A tuple with (latitude, longitude).
    """
    base_url = "https://maps.googleapis.com/maps/api/geocode/json"
    params = {
        "address": address,
        "key": api_key
    }

    response = requests.get(base_url, params=params)
    if response.status_code == 200:
        data = response.json()
        if data['status'] == 'OK':
            # Extract latitude and longitude
            location = data['results'][0]['geometry']['location']
            return location['lat'], location['lng']
        else:
            raise ValueError(f"Geocoding failed with status: {data['status']}")
    else:
        response.raise_for_status()

def std_codes(code):
    if str(code).replace('.','').isdigit():
        return(str(int(code))).replace('_x000D_\n', '').replace('\n', '')
    else:
        return (str(code)
                .replace('_x000D_\n', '')
                .replace('\n', '')
                .replace('.',''))
    

API_KEY = 'AIzaSyB4aq_pvbkaeGga3SHTvG8nj5jBBAdJpH8'

## Abastecedores

In [4]:
path = r"C:\Users\tbekho01.ATKEARNEY_AD\Kearney\Gran Coffee - Otimização de despesas operacionais - Project Management\5. Working Folder\24. Handover\250826_Otimização de Abastecedores_vEnviado\Dados Raw\Rotas para Análise\Rotas SP - Kearney - Handover.xlsx"

large_office_df = pd.read_excel(path, skiprows=1)

large_office_df

,FILIAL,CONTRATO,PARCEIRO,PATRIMÔNIO,"PATRIMONIO sem ""0""",MODELO,CAPACIDADE EM DOSES,TIPO DE MAQUINA,PDV,CLIENTE,...,HOSPITAL / LABORATÓRIO,Dia de Inventário,Seg,Ter,Qua,Qui,Sex,Sáb,Dom,Frequência Atual
0,SP,24347.0,60146.0,4862,4862,MAQ SUPER-AUTOMATICA SAECO INTELIA,100,BEBIDAS QUENTES,COPA TÉRREO,11° CARTÓRIO,...,NaN,QUINTA-FEIRA,X,X,X,X,X,NaN,NaN,5
1,SP,24347.0,60146.0,082001,82001,MAQ VENDING BQ NECTA BRIO 250,250,BEBIDAS QUENTES,TÉRREO,11° CARTÓRIO,...,NaN,QUINTA-FEIRA,X,X,X,X,X,NaN,NaN,5
2,SP,30504.0,908079.0,10653,10653,MAQ VENDING BQ NECTA COLIBRI C4,500,BEBIDAS QUENTES,COPA,CONSELHO TUTELAR - PERUS,...,NaN,TERÇA-FEIRA,X,NaN,X,NaN,X,NaN,NaN,3
3,SP,19571.0,73456.0,A16962,A16962,MAQ VENDING BQ COFFEEMAX III STD GER. II,120,BEBIDAS QUENTES,1 ANDAR,2ºCARTORIO,...,NaN,TERÇA-FEIRA,X,X,X,X,X,NaN,NaN,5
4,SP,35477.0,35614.0,028666,28666,MAQ VENDING BQ NW KREA ONE TOUCH,220,BEBIDAS QUENTES,10 ANDAR COPA,99 TAXIS,...,NaN,QUARTA-FEIRA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3553,SP,38024.0,25158.0,031829,31829,MAQ VENDING BQ NW KREA ONE TOUCH,220,BEBIDAS QUENTES,NaN,YAMAHA JANDIRA,...,NaN,SEXTA-FEIRA,X,X,X,X,X,NaN,NaN,5
3554,SP,38024.0,25158.0,031831,31831,MAQ VENDING BQ NW KREA ONE TOUCH,220,BEBIDAS QUENTES,NaN,YAMAHA JANDIRA,...,NaN,SEXTA-FEIRA,X,X,X,X,X,NaN,NaN,5
3555,SP,38024.0,25158.0,034756,34756,MAQ VENDING BQ NW KREA ONE TOUCH,220,BEBIDAS QUENTES,NaN,YAMAHA JANDIRA,...,NaN,SEXTA-FEIRA,X,X,X,X,X,NaN,NaN,5
3556,SP,38024.0,25158.0,030905,30905,MAQ VENDING BQ NW KREA ONE TOUCH,220,BEBIDAS QUENTES,COPA,YAMAHA JANDIRA,...,NaN,SEXTA-FEIRA,X,X,X,X,X,NaN,NaN,5
3557,SP,1538.0,7286.0,3465,3465,MAQ VENDING BQ NECTA KIKKO MAXXI,600,BEBIDAS QUENTES,TERREO,SODEXO MATRIZ,...,NaN,TERÇA-FEIRA,X,X,X,X,X,NaN,NaN,5

In [5]:
    
large_office_df['CLIENTE AJUSTADO'] = large_office_df['CLIENTE'].apply(std_codes)
large_office_df['ENDEREÇO AJUSTADO'] = large_office_df['ENDEREÇO'].apply(std_codes)
large_office_df['PATRIMÔNIOS AJUSTADA'] = large_office_df['PATRIMÔNIO'].apply(std_codes)

In [7]:
large_office_df["SUPERVISOR"].unique()

large_office_handover = large_office_df[
    (large_office_df["SUPERVISOR"].isin(["ANDRÉ", "ALAN FONTES"])) &
    (large_office_df["TIPO DE ATENDIMENTO CORRIGIDO"] != "FIXO")
]

In [8]:
large_office_handover

,FILIAL,CONTRATO,PARCEIRO,PATRIMÔNIO,"PATRIMONIO sem ""0""",MODELO,CAPACIDADE EM DOSES,TIPO DE MAQUINA,PDV,CLIENTE,...,Ter,Qua,Qui,Sex,Sáb,Dom,Frequência Atual,CLIENTE AJUSTADO,ENDEREÇO AJUSTADO,PATRIMÔNIOS AJUSTADA
4,SP,35477.0,35614.0,028666,28666,MAQ VENDING BQ NW KREA ONE TOUCH,220,BEBIDAS QUENTES,10 ANDAR COPA,99 TAXIS,...,NaN,NaN,NaN,NaN,NaN,NaN,-,99 TAXIS,"AVENIDA PAULISTA, N 2537 - BELA VISTA - SAO PA...",28666
5,SP,35477.0,35614.0,033465,33465,MAQ VENDING BQ NW KREA ONE TOUCH,220,BEBIDAS QUENTES,7 ANDAR,99 TAXIS,...,NaN,NaN,NaN,NaN,NaN,NaN,-,99 TAXIS,"AVENIDA PAULISTA, N 2537 - BELA VISTA - SAO PA...",33465
6,SP,35477.0,35614.0,28501,28501,MAQ VENDING BQ NW KREA ONE TOUCH,220,BEBIDAS QUENTES,7 ANDAR,99 TAXIS,...,X,X,X,X,NaN,NaN,5,99 TAXIS,"AVENIDA PAULISTA, N 2537 - BELA VISTA - SAO PA...",28501
7,SP,43179.0,35614.0,034757,34757,MAQ VENDING BQ NW KREA ONE TOUCH,220,BEBIDAS QUENTES,NaN,99 TAXIS,...,NaN,NaN,NaN,NaN,NaN,NaN,-,99 TAXIS,"AVENIDA PAULISTA, N 2537 - BELA VISTA - SAO PA...",34757
8,SP,35477.0,35614.0,030933,30933,MAQ VENDING BQ NW KREA,220,BEBIDAS QUENTES,5 ANDAR,99 TAXIS,...,X,X,X,X,NaN,NaN,5,99 TAXIS,"AVENIDA PAULISTA, N 2537 - BELA VISTA - SAO PA...",30933
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3459,SP,2922.0,75.0,8182,8182,MAQ VENDING BQ BIANCHI LEI 400,400,BEBIDAS QUENTES,BLOCO B 8° ANDAR,VIVO HUMBERTO,...,NaN,NaN,NaN,NaN,NaN,NaN,-,VIVO HUMBERTO,"R HUMBERTO I, 880 - VILA MARIANA, SÃO PAULO -...",8182
3460,SP,2922.0,75.0,8169,8169,MAQ VENDING BQ BIANCHI LEI 400,400,BEBIDAS QUENTES,BLOCO B 7° ANDAR,VIVO HUMBERTO,...,NaN,NaN,NaN,NaN,NaN,NaN,-,VIVO HUMBERTO,"R HUMBERTO I, 880 - VILA MARIANA, SÃO PAULO -...",8169
3462,SP,2922.0,75.0,8262,8262,MAQ VENDING BQ BIANCHI BVM 921,200,BEBIDAS QUENTES,RECEPCAO,VIVO OSASCO,...,X,NaN,X,NaN,NaN,NaN,2,VIVO OSASCO,"RUA ALBINO DOS SANTOS, 175 - CENTRO - OSASCO/S...",8262
3498,SP,41600.0,1019195.0,13518,13518,MAQ VENDING BQ BIANCHI LEI 400,400,BEBIDAS QUENTES,1 ANDAR BLOCO B,VOTORANTIM - LEOPOLDINA,...,X,X,X,X,NaN,NaN,5,VOTORANTIM - LEOPOLDINA,"AV MANUEL BANDEIRA, N 291 - BLOCO B 1 ANDAR - ...",13518
3542,SP,37939.0,485163.0,033466,33466,MAQ VENDING BQ NW KREA,220,BEBIDAS QUENTES,1 ANDAR - COPA,WIPRO ALPHAVILLE,...,X,X,X,X,NaN,NaN,5,WIPRO ALPHAVILLE,"AL RIO NEGRO, 585 - ALPHAVILLE INDUSTRIAL - BA...",33466

In [9]:

clientes_com_multiplos_enderecos = large_office_handover.groupby('CLIENTE AJUSTADO')['ENDEREÇO AJUSTADO'].nunique()

# Filtrar os clientes que têm mais de um endereço ajustado

# Exibir o resultado
clientes_com_multiplos_enderecos.sort_values()

CLIENTE AJUSTADO
99 TAXIS                                   1
AC CAMARGO - 7 DE ABRIL                    1
AGU - BELA VISTA                           1
AGU - OSASCO                               1
ALBERT EINSTEIN CENTER 3                   1
                                          ..
VIVO FAUSTO                                1
WIPRO ALPHAVILLE                           1
AASP                                       2
ALBERT EINSTEIN (CLINICAS ) IBIRAPUERA     2
QUALICORP                                  2
Name: ENDEREÇO AJUSTADO, Length: 200, dtype: int64

In [10]:
large_office_handover['KEY CLIENTE ENDEREÇO']=large_office_handover["CLIENTE AJUSTADO"] + " " + large_office_handover["ENDEREÇO AJUSTADO"]


filtered_addresses = large_office_handover['KEY CLIENTE ENDEREÇO'].unique()

len(filtered_addresses)

C:\Users\tbekho01.ATKEARNEY_AD\AppData\Local\Temp\ipykernel_10940\627036802.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  large_office_handover['KEY CLIENTE ENDEREÇO']=large_office_handover["CLIENTE AJUSTADO"] + " " + large_office_handover["ENDEREÇO AJUSTADO"]

203

In [11]:
filtered_addresses

array(['99 TAXIS AVENIDA PAULISTA, N 2537 - BELA VISTA - SAO PAULO/SP - 01311-300',
       'AASP  R ALVARES PENTEADO, 151 - CENTRO - SAO PAULO/SP - 01012-905',
       'AASP  R ALAMEDA SANTOS, 2159 - JD PAULISTA - SAO PAULO/SP - 01419-100',
       'AC CAMARGO - 7 DE ABRIL RUA SETE DE ABRIL, N 230 - BLOCO B - 9 ANDAR - REPUBLICA/SP - 01044-000',
       'DASA - LV LEFORTE ALPHAVILLE ALAMEDA ARAGUAIA, N 943 - ALPHAVILLE - BARUERI - SAO PAULO',
       'AGU - BELA VISTA RUA BELA CINTRA, N 657 - BELA VISTA - SAO PAULO/SP',
       'AGU - OSASCO AVENIDA DIONYSIA ALVES BARRETO - N 233 - VILA OSASCO - OSASCO/SP',
       'ALBERT EINSTEIN - ALTO DE PINHEIROS AV SAO GUALTER, 765 - ALTO DE PINHEIROS - SAO PAULO/SP - 05455-001',
       'ALBERT EINSTEIN (CLINICAS ) IBIRAPUERA  AV REPUBLICA DO LIBANO, 501 - IBIRAPUERA - SAO PAULO/SP - 04501-000',
       'ALBERT EINSTEIN (CLINICAS ) IBIRAPUERA  AV REPUBLICA DO LIBANO, 315 - IBIRAPUERA - SAO PAULO/SP - 04501-000',
       'ALBERT EINSTEIN CENTER 3  AV PAULISTA, 2064 - BELA VISTA - SAO PAULO/SP - 01310-929',
       'ALBERT EINSTEIN MBA  AVENIDA PAULISTA, 2300 - SÃO PAULO/ SP - 01310-300',
       'ALBERT EINSTEN ALPHAVILLE AV JURUA, 706 - ALPHAVILLE INDUSTRIAL - BARUERI/SP - 06455-010',
       'ALCON - BARUERI AVENIDA TAMBORE, 450 - TAMBORE - BARUERI/SP - 06460-000',
       'ALELO - VELOE ALAMEDA XINGU, N 512, EDIFICIO EVOLUTION - APHALVILLE - BARUERI/SP - 06455-030',
       'ALPER CONSULTORIA RUA LIBERO BADARO, N 158 CONJ 17 ANDAR - CENTRO - SAO PAULO/SP',
       'ALSTOM RUA ANTONIO NAGIB IBRAHIM, 400 - AGUA BRANCA - SÃO PAULO - SP 05037030',
       'AMAZON BARUERI - VERZANI E SANDRINE - GRU1 AV CECI, N 1900, TAMBORE - BARUERI/SP - 06460-120',
       'AMAZON BARUERI - VERZANI E SANDRINE - GRU50 AV CECI, N 1850, TAMBORE - BARUERI/SP - 06460-120',
       'AMAZON BARUERI - VERZANI E SANDRINE - GRU51 AV CECI, N 1700, TAMBORE - BARUERI/SP - 06460-120',
       'AMAZON BARUERI - VERZANI E SANDRINE - GRU53 AV CECI, N 1600, TAMBORE - BARUERI/SP - 06460-120',
       'AMAZON BARUERI - VERZANI E SANDRINE - GRU54 AV CECI, N 1649, TAMBORE - BARUERI/SP - 06460-120',
       'AMAZON SÃO PAULO - DBZ1 AVENIDA EMBAIXADOR MACEDO SOARES, 10735 - PARQUE RESIDENCIAL DA LAPA - SAO PAULO/SP - 05095-035',
       'ASSURANT ALAMEDA RIO NEGRO, 585 - ALPHAVILLE - BARUERI/SP - 06454-000',
       'ATENTO - SAO BENTO I RUA LIBERO BADARO, N 633/641 - CENTRO - SAO PAULO/SP - 01009-000',
       'ATENTO - SAO BENTO II LAGO SAO BENTO, N 64 - CENTRO - SAO PAULO/SP- 01029-900',
       'BANCO ALFA RUA BELA CINTRA, N 560 - CERQUEIRA CESAR - SAO PAULO/SP - 01418-000',
       'BANCO SAFRA BELA CINTRA  R BELA CINTRA, 560 - JD AMERICA -SAO PAULO/SP - 01415-000',
       'BANCO SAFRA MATRIZ  AV PAULISTA, 2100 - CERQUEIRA CESAR - SAO PAULO/SP - 01310-930',
       'BANCO SAFRA PREDIO J  AV PAULISTA, 2150 - CERQUEIRA CESAR - SAO PAULO/SP - 01310-930',
       'BANCO SOCIETE GENERALI  AVENIDA PAULISTA, 2300 - SÃO PAULO/ SP - 01310-300',
       'BANCO SOFISA AL SANTOS, N 1496 - JARDIM PAULISTA - SAO PAULO/SP - 01418-100',
       'BAT BRASIL - SOUZA CRUZ AVENIDA REBOUCAS, 10145 - PINHEIROS - SAO PAULO/SP - 05401-150',
       'BESNI  RUA 24 DE MAIO, 195',
       'BIO BRANDS RUA BONNARD, N 980 - ALPHAVILLE - CENTRO INDUSTRIAL E EMPRESARIAL - BARUERI - SAO PAULO/SP - 06454-020',
       'BIOFAST - OSASCO RUA ELOY CANDIDO LOPES, 381 - CENTRO - OSASCO/SP - 06010-130',
       'BOTICARIO ACADEMIA R OSCAR FREIRE, N 1375 - PINHEIROS - SAO PAULO/SP - 05409-010',
       'BRADESCO - LEOPOLDINA RUA DR SEIDEL, 425 VILA LEOPOLDINA - SAO PAULO/SP - 05315-000',
       'BRADY SETON AV CECI, 238 - TAMBORE - BARUERI - SP    ',
       'CAIXA VIDA E PREVIDENCIA - BARUERI ALAMEDA ARAGUAIA, N 2104 - 23 ANDAR - ALPHAVILLE - BARUERI/SP - 06455-000',
       'CAMPARI AL RIO NEGRO, 585 - ALPHAVILLE - BARUERI/SP - 06454-000',
       'CDB - ANA ROSA AVENIDA CONSELHEIRO RODRIGUES ALVES, 300 - VILA MARIANA - SP',
       'CENTRO UNIVERSITARIO FEI RUA TAMANDARE, N 688, LIBERDADE - LIBERDADE - SAO PAULO/SP - 06460-000',
       'CHIESI FARMACEUTICA R DR GIACOMO CHIESI, N 151- KM 39,2 - ESTR ROMEIROS - VOTUPARIM - SANTANA DE PARNAIBA/SP - 06513-005',
       'CIDADE II MÊTRO RUA BOA VISTA, 175 - CENTRO',
       'CLEARTECH ALAMEDA RIO NEGRO, N 585 - ALPHAVILLE - BARUERI/SP - 06454-000',
       'CLINICA FARES OSASCO AV ANTONIO AGU, 630 - CENTRO OSASCO CEP 06093-006',
       'CONDOMINIO EPVL RUA MAJOR DE PALADINO, N 128 - VILA RIBEIRO DE BARROS - SÃO PAULO/SP - 05307-000',
       'CONDOMINIO LONG STAY BELA CINTRA RUA BELA CINTRA, N 521 - CERQUEIRA CESAR - SAO PAULO/SP - 03021-020',
       'CROWE RUA QUINZE DE NOVEMBRO, 184 ANDAR - CENTRO , SAO PAULO/SP - 01013000',
       'CRUZEIRO DO SUL - LIBERDADE RUA GALVAO BUENO, 868 - LIBERDADE - SAO PAULO/SP - 01506-000',
       'CRUZEIRO DO SUL - PAULISTA AV PAULISTA, 1415 - BELA VISTA - SAO PAULO/SP - 01311-925',
       'CRUZEIRO DO SUL - VILA LOBOS AV IMPERATRIZ LEOPOLDINA, 550 - VILA LEOPOLDINA - SAO PAULO/SP - 05305-000',
       'CUSHMAN - ERICSSON ALAMEDA ARAGUAIA, 2104 - EDCEA CORPORATE - TORRE1 - 15 ANDAR - REFEITORIO - ALPHAVILLE INDUSTRIAL - BARUERI/SP - 06455-000',
       'CYRELA PAULISTA AVENIDA PAULISTA, N 1063 - JARDIM PAULISTA - SAO PAULO/SP',
       'DASA - H9J AV CAUAXI, 64/118 - ALPHAVILLE - BARUERI/SP - 06454-020',
       'DASA - LV-VILA LEOPOLDINA AV IMPERATRIZ LEOPOLDINA, 1554 - VILA LEOPOLDINA - SAO PAULO/SP - 05305-002',
       'DASA CECI AV CECI, 426 TAMBORE - BARUERI/SP - 06460-120',
       'DASA LIBERDADE GALVAO BUENO, N 257 - LIBERDADE - SAO PAULO/SP - 01506-000',
       'DASA TAMBORÉ AV TAMBAQUI, 113 - TAMBORÉ',
       'DELBONI - AUGUSTA RUA AUGUSTA, 1828 - JARDIM PAULISTA - SP',
       'DELBONI JURUA AV JURUA, 434  - ALPHAVILLE INDUSTRIAL - BARUERI - SP',
       'DEXCO SA AVENIDA PAULISTA, N 1938 - BELA VISTA - SAO PAULO/SP - 01310-942',
       'DIGIO ALAMEDA XINGU, N 512 - ALPHAVILLE - BARUERI/SP - 06455-030',
       'DURATEX - DECA RUA COMENDADOR SOUSA, N 135 - AGUA BRANCA - SAO PAULO/SP - 05037-090',
       'ECAD SP AV PAULISTA, N 171 - PARAISO - SAO PAULO/SP',
       'EINSTEIN VILA MARIANA  R CORONEL LISBOA, 139 - VL MARIANA - SAO PAULO/SP - 04020-040',
       'ELOPAR ALAMEDA XINGU, N 512 - ALPHAVILLE - BARUERI/SP - 06455-030',
       'EMBRATEL - INGLESES R DOS INGLESES, 600 - MORRO DOS INGLESES - SAO PAULO/SP - 01329-904',
       'EMBRATEL - LAPA R ALDO DE AZEVEDO, 200 - LAPA - SAO PAULO/SP - 05453-030',
       'EUROP ASSISTENCE AVENIDA JURUA, 320 - BARUERI/SP',
       'FACULDADE SAO LEOPOLDO MANDIC RUA ITAPEVA, 538 - BELA VISTA - SAO PAULO/SP - 01332-020',
       'FDE AV SAO LUIS, N 99 - REPUBLICA - SAO PAULO/SP - 01046-001',
       'FGV RUA DOUTOR PLINIO BARRETO, 365 - BELA VISTA - SAO PAULO/SP',
       'FIRST DATA - PAULISTA AV PAULISTA, N 2300 - BELA VISTA SAO PAULO/SP',
       'FLORA ALAMEDA ARAGUAIA, 211 - ALPHAVILLE INDUSTRIAL - BARUERI/SP - 06455-000',
       'FLORA - AUTO PEÇAS AVENIDA FLORA, N 65 - JAGUARIBE - OSASCO/SP - 06053-040',
       'FLORA TAMBORE ALAMEDA ARAGUAIA, N 3600 - ALPHAVILLE - BARUERI/SP - 06455-000',
       'FRESENIUS AV MARGINAL PROJETADA , 1652',
       'GE BAND AVENIDA EMBAIXADOR MACEDO SOARES, 10001 - VL ANASTACIO - SÃO PAULO/SP - 05035-035',
       'GE HEALTHCARE AV MARCOS PENTEADO DE ULHOA RODRIGUES, 690 - BARUERI/SP - 06460-040',
       'GLOBO ALAMEDA SANTOS  ALAMEDA SANTOS,700',
       'GO OFFICES LATAM AVENIDA PAULISTA, N 475 - CERQUEIRA CESAR - SAO PAULO/SP - 04039-004',
       'GRANCOFFEE FILIAL SP RUA MAJOR PALADINO,128 - GALPAO 4 - VILA LEOPOLDINA - SAO PAULO/SP',
       'HARALD FABRICA ESTR ANA PROCOPIO DE MORAES, 745 - VARZEA DE SOUZA - SANTANA DE PARNAIBA',
       'HARALD MATRIZ RUA MUNDO, 378 JARDIM SILVIO - SANTANA DE PARNAÍBA - SP - CEP: 05528-451',
       'HEINEKEN - CDA OSASCO R HENRY FORD, N 803 - PRESIDENTE ALTINO - OSASCO/SP',
       'GREEN4T - BARUERI AV GUPE, N 10767 - JARDIM BELVAL - BARUERI/SP - 06422-120',
       'HOSPITAL ALBERT EINSTEIN - ARTHUR DE AZEVEDO RUA ARTHUR DE AZEVEDO, N 411 - PINHEIROS - SAO PAULO/SP - 05404010',
       'HOSPITAL SAHA RUA MAESTRO CARDIM, 407',
       'HYPERMARCAS COSMED AV CECI, 282 - CENTRO EMPR TAMBORE - BARUERI/SP - 06460-120',
       'HYPERMARCAS HYNOVA AV ANDROMEDA, 2000 - ALPHAVILLE EMP - BARUERI/SP - 05676-120',
       'ICESP OSASCO R BENEDITO AMERICO DE OLIVEIRA,122 - VILA YARA - OSASCO - SP 06028-080',
       'INDORAMA - OXITENO ALAMEDA SANTOS, N 960 - CERQUEIRA CESAR - SAO PAULO/SP',
       'INOVA SAUDE SAO PAULO AVENIDA RIO BRANCO, N 1114 - CAMPOS ELISEOS - SAO PAULO/SP - 01206-001',
       'INSTITUTO PHORTE DE EDUCACAO RUA TREZE DE MAIO 681, BELA VISTA - SAO PAULO/SP - 01327-000',
       'INTERMÉDICA CARAPICUIBA AV TAMARA, 311 ANTIGO 60 - CARAPICUIBA - SP 06320-020',
       'INTERMÉDICA ALPHAVILLE AL AMAZONAS, 329 - BARUERI - SP 06454-070',
       'INTERMÉDICA LAPA RUA BATALHA DO PIRAJA, 157 - LAPA - SÃO PAULO - SP - 05065-120',
       'INTERMÉDICA NOTRELABS POLVILHO AVENIDA TENENTE MARQUES, 1795 - PARAISO POLVILHO - CAJAMAR',
       'INTERMÉDICA OSASCO AV DOS AUTONOMISTAS 2502 - OSASCO - SP 06090-010',
       'INTERMÉDICA PAULISTA  AV PAULISTA, 777',
       'IT WORKS ALAMEDA RIO NEGRO, N 585 - ALPHAVILLE - BARUERI/SP - 06454-000',
       'ITAU - AV PAULISTA AV PAULISTA, N 1374 - BELA VISTA - SAO PAULO/SP - 01310-100',
       'ITAU BARUERI ( SO LEITURA) AL TOCANTINS 125 28 ANDAR ALPHAVILLE',
       'ITAÚ UNIBANCO - AFACI - SP  PRACA PADRE MANOEL DA NOBREGA, 21 - SAO PAULO/SP - 01015-010',
       'ITAUSA  AV PAULISTA, 1938 - BELA VISTA - SAO PAULO/SP - 01310200',
       'KERRY - BARUERI ALAMEDA ARAPOEMA, 480 - TAMBORE, BARUERI/SP - 06460080',
       'KOVI AV RAIMUNDO PEREIRA DE MAGALHAES, N 136 - VILA ANASTACIO - SAO PAULO/SP - 05092-040',
       'LAVOISIER ALPHAVILLE ALAMEDA RIO NEGRO, 967 - ALPHAVILLE INDUSTRIAL, BARUERI - SP, 06454-000 ',
       'LAVOISIER LAPA1 R TOME DE SOUZA, 197 - LAPA - SAO PAULO/SP - 05079000',
       'LAVOISIER LAPA2 R TOME DE SOUZA, 220 - LAPA - SAO PAULO/SP - 05079000',
       'LAVOISIER QUITAÚNA RUA JEQUIE 98 -QUITAÚNA',
       'LAVOISIER REPUBLICA AV DR VIEIRA DE CARVALHO, N 176 - REPUBLICA - SAO PAULO/SP - 01210-010',
       'LAVOISIER SHOPUNIÃO AV DOS AUTONOMISTAS, 1400 - VILA YARA - OSASCO - SP - 06020010',
       'LEFORTE LIBERDADE  R GALVAO BUENO, 257 / 290 / 412- 1 ANDAR - LIBERDADE - SAO PAULO/SP',
       'LELLO OSCAR FREIRE RUA OSCAR FREIRE, 667 - JARDIM PAULISTA - SAO PAULO/SP - 01426-003',
       'LELLO PAULISTA AV PAULISTA, 302',
       'LIVELO ALAMEDA XINGU, N 512 - ALPHAVILLE - BARUERI/SP - 06455-030',
       'LOCALIZA - PAULISTA ALAMEDA SANTOS, N 1826 - JARDIM PAULISTA - SAO PAULO/SP - 01418-102',
       'LOG FRIO LOGISTICA RUA JUSSARA, 1635 - SALA L - CAMARA 1 - JARDIM SANTA CECILIA - BARUERI/SP - 06465-070',
       'LOGICALIS - BARUERI AV TAMBORE, N 267 - BARUERI/SP - 06460-000',
       'LOGICALIS - WESERVICE AV TAMBORE, N 267 - BARUERI/SP - 06460-000',
       'MATCHEM - SANTANA DE PARNAIBA RUA SAO PAULO, N 92 - JARDIM VARZEA - SANTANA DE PARNAIBA',
       'METRICS AVENIDA PAULISTA, 302 - 12 ANDAR SALA 82 - BELA VISTA - SAO PAULO/SP - 01310-000',
       'METRO CCO  RUA VERGUEIRO, 1200 - LIBERDADE - SAO PAULO/SP - 01504-000',
       'MELHORAMENTOS LAPA R TITO, 479 - LAPA - SAO PAULO - SP 05051-000',
       'METTLER AVENIDA TAMBORE, 418 - TAMBORE - BARUERI/SP - 06460-000',
       'MINERACAO TABOCA ALAMEDA RIO NEGRO 161, 5 ANDAR',
       'MITRE HEALTHY ALAMEDA SANTOS, N 700 - CERQUEIRA CESAR/SP - 01418-002',
       'ML GOMES SAO PAULO RUA 15 DE NOVEMBRO, N 137 - CENTRO - SAO PAULO/SP - 01013-000',
       'NEOBPO  AVENIDA IPIRANGA, 855 - CENTRO - SP',
       'NEOBPO SÃO JOAO RUA CONSELHEIRO DE NEBIAS, 14',
       'NOKIA RUA WERNER VON SIEMENS, 111 - PREDIO 25  BLOBO C  1 ANDAR E - BUSINESS - LAPA',
       'NOTRELAB INTERMÉDICA - OSASCO AV:AVENIDA DOS AUTONOMISTAS 2515',
       'NOTRELABS UNIDADE ITABUNA R ITABUNA, N 76 - CENTRO - OSASCO/SP',
       'NUBANK AVENIDA JOSE CESAR DE OLIVEIRA, 21 - VILA LEOPOLDINA - SAO PAULO/SP - 05317-000',
       'ODONTOPREV ALAMEDA ARAGUAIA, 2104 - 20 ANDAR - CENTRO EMPRESARIAL ALPHAVILLE - ALPHAVILE - BARUERI/SP - 06455-000',
       'OLX SP AVENIDA PAULISTA, N 1106 - BELA VISTA - SAO PAULO/SP - 01310-100',
       'OLYMPUS OPTICAL ALAMEDA ARAGUAIA, N 2104 - 18 ANDAR - SALA 181-A, 182-A, 183-A E 184-A - ALPHAVILLE INDUSTRIAL - BARUERI - SAO PAULO/SP - 06455-000',
       'ORIGINAL TOKYO OSASCO AVENIDA DOS AUTONOMISTAS, N 1155 - VILA IARA - OSASCO/SP',
       'POIESIS - ORGANIZACAO SOCIAL DE CULTURA RUA LIBERO BADARO, N 377 - CENTRO - SAO PAULO/SP',
       'POLIEDRO AVENIDA BERNARDINO DE CAMPOS, N 268 - PARAISO - SAO PAULO/SP - 04004-041',
       'POLIEDRO - VILA MARIANA R MADRE CABRINI,38 - - VILA MARIANA - 04020-000 - SAO PAULO-SP',
       'PWC AV MARCOS PENTEADO DE ULHOA RODRIGUES, 939 - TAMBORÉ, BARUERI - SP',
       'QUALICORP AVENIDA PAULISTA, N 1106 - SAO PAULO - CONSOLACAO - SAO PAULO/SP - 01311-300',
       'QUALICORP AL XINGU, 512 - 15° E 16° ANDAR - ALPHAVILLE - BARUERI/SP - 06455-030',
       'QUOD ALAMEDA ARAGUAIA 2104 - BARUERI/SP - 06455-000',
       'RIACHUELO - LEOPOLDINA AVENIDA MOFARREJ, N 825 - VILA LEOPOLDINA - SAO PAULO/SP - 05311-000',
       'RIR RUA HELIOPOLIS, 281 - 05318-030 - VILA LEOPOLDINA - SÃO PAULO-SP',
       'SALOMAO E ZOPPI  RUA CUBATAO, 587 ',
       'SALOMAO E ZOPPI - LAPA RUA CERRO CORÁ, 1044  - VILA ROMANA, SÃO PAULO/SP - 05061200',
       'SALOMAO E ZOPPI - OSASCO AV DOS AUTONOMISTAS, 2632  - CENTRO, OSASCO/SP - 06090010',
       'SALOMAO E ZOPPI - PARAISO RUA CORREIA DIAS, 136 - FAZENDA CASTELO, SAO PAULO/SP - 04104000',
       'SCALA ALPHAVILLE CECI - TB01 AVENIDA CECI, N 1900 - ALPHAVILLE - BARUERI/SP - 06460-120',
       'SCALA ALPHAVILLE CECI - TB03 AVENIDA CECI, N 1700 - ALPHAVILLE - BARUERI/SP - 06460-120',
       'SCALA ALPHAVILLE CECI - TB08 AVENIDA CECI, N 1649 - ALPHAVILLE - BARUERI/SP - 06460-120',
       'SCALA ALPHAVILLE TOCANTINS ALAMEDA TOCANTINS, N 350, - ALPHAVILLE - BARUERI/SP - 06455-020',
       'SCALA DATA CENTERS - CANTEIRO EHS AV CECI, 1649  - TAMBORE, BARUERI/SP - 06460120',
       'SCALA DATA CENTERS - CANTEIRO TB12 R JOAO FERREIRA DE CAMARGO, 864 - TAMBORE, BARUERI - SP, 06460-060',
       'SCALA DATA CENTERS - MUTINGA RUA VICTORINO 207 - JARDIM MUTINGA - BARUERI/SP, 06463-290',
       'SCALA DATA CENTERS - UN TB04 AVENIDA CECI, 1500 - TAMBORE - BARUERI/SP - 06460-120',
       'SCALA DATA CENTERS - UN TB05 AVENIDA CECI, 1500 - TAMBORE - BARUERI/SP - 06460-120',
       'SCALA DATA CENTERS - UN TB12 AVENIDA CECI, 1649 - TAMBORE - BARUERI/SP - 06460-120',
       'SEAL TELECOM RUA MAJOR PALADINO, 128 - GALPAO 8 - VILA RIBEIRO DE BARROS - SAO PAULO/SP - 05307-000',
       'SEM PARAR AVENIDA IMPERATRIZ LEOPOLDINA, N 1661 - VL HAMBURGUESA - SAO PAULO/SP - 05305-007',
       'SEM PARAR - CTF AVENIDA IMPERATRIZ LEOPOLDINA, N 1661 - VL HAMBURGUESA - SAO PAULO/SP - 05305-007',
       'SEMPRE ENGENHARIA RUA TREZE DE MAIO, N 1633 - BELA VISTA - SAO PAULO/SP - 04039-004',
       'SETTER - APMINISTÉRIO PUBLICO RUA RIACHUELO, 115 - CENTRO',
       'SKY AV MARCOS PENTEADO ULHOA RODRIGUES, 1000, STNA DO PARNAIBA',
       'SODEXO - TETRAPAK AV AV DAS NACOES UNIDAS, 4777 - SÃO PAULO/SP',
       'SOFTWARE  AVENIDA PAULISTA, 2300 - SÃO PAULO/ SP - 01310-300',
       'SOMOS EDUCAÇAO PAULISTA    AV PAULISTA, 901 - BELA VISTA, SÃO PAULO - SP, 01310-100',
       'SP - URBANISMO RUA LIBERO BADARO, N 504 - EDIFICIO MARNELLI - CENTRO - SAO PAULO/SP - 01008-906',
       'TDS INFORMATICA AL ARAGUAIA, 2044 - ALPHAVILLE - BARUERI/SP - 06455-000',
       'TECBAN ALPHAVILLE AV ANDROMEDA, N 2000, BLOCO 1 - NV 3 BL 2 NVS 4, 5 - ALPHAVILLE EMPRESARIAL - BARUERI/SP - 03010-000',
       'TEL TELEMATICA ALAMEDA TOCANTINS, 350 - ALPHAVILLE - BARUERI/SP - 06455-020',
       'TEMPO AV ANDRÔMEDA, 2000 - ALPHAVILLE, BARUERI - SP, 06473-000',
       'TMF AVENIDA MARCOS PENTEADO DE ULHÔA RODRIGUES ,939 - TAMBORÉ - BARUERI/SP',
       'TOKIO 13 DE MAIO  RUA TREZE DE MAIO, 1529 - BELA VISTA - SAO PAULO - SP',
       'TOKIO CHAP CHAP  RUA TREZE DE MAIO, 1563 - BELA VISTA - SAO PAULO - SP',
       'TOKIO MARINE - ARTUR PRADO RUA ARTUR PRADO, N 659 - 1 ANDAR - BELA VISTA - SAO PAULO/SP - 01322-000',
       'TOKIO MARINE - PARAÍSO RUA CUBATÃO, 86 - PARAÍSO, SAO PAULO',
       'TOKIO MARINE SAMPAIO  RUA DOUTOR SAMPAIO VIANA, 44 - PARAISO - SP',
       'TOP ONE SAUDE RUA MARTINS FONTES, N 91 CONJUNTO 72 - CENTRO - SAO PAULO/SP - 01050-905',
       'TOYOTA ALAMEDA TOCANTINS, 955 - ALPHAVILLE - BARUERI/SP, 06455-020',
       'UNIMED - PAMPLONA RUA PAMPLONA, N 1625 - JARDIM PAULISTA - SAO PAULO/SP - 01405-002',
       'UNIMED CNU - AIS ALAMEDA SANTOS, N 1827 - CERQUEIRA CESAR - SAO PAULO/SP - 01418-102',
       'UNIMED CNU - FREI CANECA RUA FREI CANECA, 1355 - SÃO PAULO-SP',
       'UNIMED FESP RUA JOSE GETULIO, 78 - LIBERDADE, SAO PAULO/SP - 01509000',
       'UNIMED JB ALAMEDA SANTOS, N 1827 - CERQUEIRA CESAR - SAO PAULO/SP - 01418-102',
       'UNIMED SEGUROS  ALAMEDA MINISTRO ROCHA DE AZEVEDO, 366 - CERQUEIRA CESAR - SP',
       'UNINOVE - OSASCO RUA DANTE BATTISTON, 107 - CENTRO - OSASCO/SP - CEP 06013-030',
       'VEOLIA AV MANOEL BANDEIRA, 291 BL A - VILA LEOPOLDINA - SAO PAULO/SP - 05317-020',
       'VERIFONE ALAMEDA PUCURUI, 88 - TAMBORE - BARUERI/SP - 06460-100',
       'VILA VELHA CORRETORA AVENIDA IPIRANGA, N 313 - REPUBLICA - SAO PAULO/SP - 06460-000',
       'VIVO - SPO ALPHAVILLE IOT ALAMEDA XINGU, 200 - ALPHAVILLE CENTRO INDUSTRIAL E EMPRESARIAL - BARUERI/SP - 06455-030',
       'VIVO CLOUD ALPHAVILLE ALAMEDA XINGU, 350 – ITOWER ALPHAVILLE - BARUERI - SÃO PAULO - 06455-000',
       'VIVO FAUSTO  RUA DOUTOR FAUSTO FERRAZ, 172 - CENTRO - SÃO PAULO/SP - 01333-030',
       'VIVO HUMBERTO   R HUMBERTO I, 880 - VILA MARIANA, SÃO PAULO - SP, 04002-010',
       'VIVO OSASCO RUA ALBINO DOS SANTOS, 175 - CENTRO - OSASCO/SP - 06093-060',
       'VOTORANTIM -  LEOPOLDINA AV MANUEL BANDEIRA, N 291 - BLOCO B 1 ANDAR - 21 B - VILA LEOPOLDINA - SAO PAULO/SP - 05317-020',
       'WIPRO ALPHAVILLE AL RIO NEGRO, 585 - ALPHAVILLE INDUSTRIAL - BARUERI/RP - 06454-000'],
      dtype=object)

In [16]:
large_office_df

,FILIAL,CONTRATO,PARCEIRO,PATRIMÔNIO,"PATRIMONIO sem ""0""",MODELO,CAPACIDADE EM DOSES,TIPO DE MAQUINA,PDV,CLIENTE,...,Ter,Qua,Qui,Sex,Sáb,Dom,Frequência Atual,CLIENTE AJUSTADO,ENDEREÇO AJUSTADO,PATRIMÔNIOS AJUSTADA
0,SP,24347.0,60146.0,4862,4862,MAQ SUPER-AUTOMATICA SAECO INTELIA,100,BEBIDAS QUENTES,COPA TÉRREO,11° CARTÓRIO,...,X,X,X,X,NaN,NaN,5,11° CARTÓRIO,R NELSON GAMA DE OLIVEIRA 235 - MORUMBI - SAO ...,4862
1,SP,24347.0,60146.0,082001,82001,MAQ VENDING BQ NECTA BRIO 250,250,BEBIDAS QUENTES,TÉRREO,11° CARTÓRIO,...,X,X,X,X,NaN,NaN,5,11° CARTÓRIO,R NELSON GAMA DE OLIVEIRA 235 - MORUMBI - SAO ...,82001
2,SP,30504.0,908079.0,10653,10653,MAQ VENDING BQ NECTA COLIBRI C4,500,BEBIDAS QUENTES,COPA,CONSELHO TUTELAR - PERUS,...,NaN,X,NaN,X,NaN,NaN,3,CONSELHO TUTELAR - PERUS,"RUA GONCALVES DE ANDRADE, N 177 - PERUS - SAO ...",10653
3,SP,19571.0,73456.0,A16962,A16962,MAQ VENDING BQ COFFEEMAX III STD GER. II,120,BEBIDAS QUENTES,1 ANDAR,2ºCARTORIO,...,X,X,X,X,NaN,NaN,5,2ºCARTORIO,"RUA VITORINO CARMILO, 576 - BARRA FUNDA - SAO ...",A16962
4,SP,35477.0,35614.0,028666,28666,MAQ VENDING BQ NW KREA ONE TOUCH,220,BEBIDAS QUENTES,10 ANDAR COPA,99 TAXIS,...,NaN,NaN,NaN,NaN,NaN,NaN,-,99 TAXIS,"AVENIDA PAULISTA, N 2537 - BELA VISTA - SAO PA...",28666
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3553,SP,38024.0,25158.0,031829,31829,MAQ VENDING BQ NW KREA ONE TOUCH,220,BEBIDAS QUENTES,NaN,YAMAHA JANDIRA,...,X,X,X,X,NaN,NaN,5,YAMAHA JANDIRA,"ESTRADA VELHA DE ITU 1045 - JANDIRA /SP, 06616...",31829
3554,SP,38024.0,25158.0,031831,31831,MAQ VENDING BQ NW KREA ONE TOUCH,220,BEBIDAS QUENTES,NaN,YAMAHA JANDIRA,...,X,X,X,X,NaN,NaN,5,YAMAHA JANDIRA,"ESTRADA VELHA DE ITU 1045 - JANDIRA /SP, 06616...",31831
3555,SP,38024.0,25158.0,034756,34756,MAQ VENDING BQ NW KREA ONE TOUCH,220,BEBIDAS QUENTES,NaN,YAMAHA JANDIRA,...,X,X,X,X,NaN,NaN,5,YAMAHA JANDIRA,"ESTRADA VELHA DE ITU 1045 - JANDIRA /SP, 06616...",34756
3556,SP,38024.0,25158.0,030905,30905,MAQ VENDING BQ NW KREA ONE TOUCH,220,BEBIDAS QUENTES,COPA,YAMAHA JANDIRA,...,X,X,X,X,NaN,NaN,5,YAMAHA JANDIRA,"ESTRADA VELHA DE ITU 1045 - JANDIRA /SP, 06616...",30905
3557,SP,1538.0,7286.0,3465,3465,MAQ VENDING BQ NECTA KIKKO MAXXI,600,BEBIDAS QUENTES,TERREO,SODEXO MATRIZ,...,X,X,X,X,NaN,NaN,5,SODEXO MATRIZ,"AV IBIRAPUERA, 1196 - INDIANOPOLIS - SAO PAULO...",3465

In [17]:
for address in filtered_addresses:
    try:
        lat, lng = get_coordinates(address, API_KEY)
        print(f"Coordinates for '{address}': Latitude = {lat}, Longitude = {lng}")

        large_office_handover.loc[large_office_handover['KEY CLIENTE ENDEREÇO'] == address, 'Latitude2'] = lat
        large_office_handover.loc[large_office_handover['KEY CLIENTE ENDEREÇO'] == address, 'Longitude2'] = lng
    except Exception as e:
        print(f"Error: {e}")

Coordinates for '99 TAXIS AVENIDA PAULISTA, N 2537 - BELA VISTA - SAO PAULO/SP - 01311-300': Latitude = -23.5564383, Longitude = -46.6628958

C:\Users\tbekho01.ATKEARNEY_AD\AppData\Local\Temp\ipykernel_10940\1978856634.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  large_office_handover.loc[large_office_handover['KEY CLIENTE ENDEREÇO'] == address, 'Latitude2'] = lat
C:\Users\tbekho01.ATKEARNEY_AD\AppData\Local\Temp\ipykernel_10940\1978856634.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  large_office_handover.loc[large_office_handover['KEY CLIENTE ENDEREÇO'] == address, 'Longitude2'] = lng

Coordinates for 'AASP  R ALVARES PENTEADO, 151 - CENTRO - SAO PAULO/SP - 01012-905': Latitude = -23.5471281, Longitude = -46.635003
Coordinates for 'AASP  R ALAMEDA SANTOS, 2159 - JD PAULISTA - SAO PAULO/SP - 01419-100': Latitude = -23.5594748, Longitude = -46.6608403
Coordinates for 'AC CAMARGO - 7 DE ABRIL RUA SETE DE ABRIL, N 230 - BLOCO B - 9 ANDAR - REPUBLICA/SP - 01044-000': Latitude = -23.5457447, Longitude = -46.6411594
Coordinates for 'DASA - LV LEFORTE ALPHAVILLE ALAMEDA ARAGUAIA, N 943 - ALPHAVILLE - BARUERI - SAO PAULO': Latitude = -23.4980966, Longitude = -46.8517402
Coordinates for 'AGU - BELA VISTA RUA BELA CINTRA, N 657 - BELA VISTA - SAO PAULO/SP': Latitude = -23.5595546, Longitude = -46.6578771
Coordinates for 'AGU - OSASCO AVENIDA DIONYSIA ALVES BARRETO - N 233 - VILA OSASCO - OSASCO/SP': Latitude = -23.5364632, Longitude = -46.7833946
Coordinates for 'ALBERT EINSTEIN - ALTO DE PINHEIROS AV SAO GUALTER, 765 - ALTO DE PINHEIROS - SAO PAULO/SP - 05455-001': Latitude = -23.5420864, Longitude = -46.7115795
Coordinates for 'ALBERT EINSTEIN (CLINICAS ) IBIRAPUERA  AV REPUBLICA DO LIBANO, 501 - IBIRAPUERA - SAO PAULO/SP - 04501-000': Latitude = -23.5846918, Longitude = -46.6634166
Coordinates for 'ALBERT EINSTEIN (CLINICAS ) IBIRAPUERA  AV REPUBLICA DO LIBANO, 315 - IBIRAPUERA - SAO PAULO/SP - 04501-000': Latitude = -23.5846918, Longitude = -46.6634166
Coordinates for 'ALBERT EINSTEIN CENTER 3  AV PAULISTA, 2064 - BELA VISTA - SAO PAULO/SP - 01310-929': Latitude = -23.5578999, Longitude = -46.6591358
Coordinates for 'ALBERT EINSTEIN MBA  AVENIDA PAULISTA, 2300 - SÃO PAULO/ SP - 01310-300': Latitude = -23.5568726, Longitude = -46.6612375
Coordinates for 'ALBERT EINSTEN ALPHAVILLE AV JURUA, 706 - ALPHAVILLE INDUSTRIAL - BARUERI/SP - 06455-010': Latitude = -23.5003802, Longitude = -46.8581401
Coordinates for 'ALCON - BARUERI AVENIDA TAMBORE, 450 - TAMBORE - BARUERI/SP - 06460-000': Latitude = -23.5017113, Longitude = -46.8426988
Coordinates for 'ALELO - VELOE ALAMEDA XINGU, N 512, EDIFICIO EVOLUTION - APHALVILLE - BARUERI/SP - 06455-030': Latitude = -23.5046677, Longitude = -46.8510711
Coordinates for 'ALPER CONSULTORIA RUA LIBERO BADARO, N 158 CONJ 17 ANDAR - CENTRO - SAO PAULO/SP': Latitude = -23.5481559, Longitude = -46.6370853
Coordinates for 'ALSTOM RUA ANTONIO NAGIB IBRAHIM, 400 - AGUA BRANCA - SÃO PAULO - SP 05037030': Latitude = -23.511873, Longitude = -46.69672
Coordinates for 'AMAZON BARUERI - VERZANI E SANDRINE - GRU1 AV CECI, N 1900, TAMBORE - BARUERI/SP - 06460-120': Latitude = -23.497589, Longitude = -46.8145765
Coordinates for 'AMAZON BARUERI - VERZANI E SANDRINE - GRU50 AV CECI, N 1850, TAMBORE - BARUERI/SP - 06460-120': Latitude = -23.4934532, Longitude = -46.8106233
Coordinates for 'AMAZON BARUERI - VERZANI E SANDRINE - GRU51 AV CECI, N 1700, TAMBORE - BARUERI/SP - 06460-120': Latitude = -23.4960499, Longitude = -46.8130538
Coordinates for 'AMAZON BARUERI - VERZANI E SANDRINE - GRU53 AV CECI, N 1600, TAMBORE - BARUERI/SP - 06460-120': Latitude = -23.4966954, Longitude = -46.81469
Coordinates for 'AMAZON BARUERI - VERZANI E SANDRINE - GRU54 AV CECI, N 1649, TAMBORE - BARUERI/SP - 06460-120': Latitude = -23.497806, Longitude = -46.8161959
Coordinates for 'AMAZON SÃO PAULO - DBZ1 AVENIDA EMBAIXADOR MACEDO SOARES, 10735 - PARQUE RESIDENCIAL DA LAPA - SAO PAULO/SP - 05095-035': Latitude = -23.510527, Longitude = -46.7184354
Coordinates for 'ASSURANT ALAMEDA RIO NEGRO, 585 - ALPHAVILLE - BARUERI/SP - 06454-000': Latitude = -23.5004973, Longitude = -46.8486757
Coordinates for 'ATENTO - SAO BENTO I RUA LIBERO BADARO, N 633/641 - CENTRO - SAO PAULO/SP - 01009-000': Latitude = -23.5441638, Longitude = -46.63493889999999
Coordinates for 'ATENTO - SAO BENTO II LAGO SAO BENTO, N 64 - CENTRO - SAO PAULO/SP- 01029-900': Latitude = -23.5441638, Longitude = -46.63493889999999
Coordinates for 'BANCO ALFA RUA BELA CINTRA, N 560 - CERQUEIRA CESAR - SAO PAULO/SP - 01418-000': Latitude = -23.5534823, Longitude = -46.65792690000001
Coordinates for 'BANCO SAFRA BELA CINTRA  R BELA CINTRA, 560 - JD AMERICA -SAO PAULO/SP - 01415-000': Latitude = -23.5534823, Longitude = -46.65792690000001
Coordinates for 'BANCO SAFRA MATRIZ  AV PAULISTA, 2100 - CERQUEIRA CESAR - SAO PAULO/SP - 01310-930': Latitude = -23.5578283, Longitude = -46.6597361
Coordinates for 'BANCO SAFRA PREDIO J  AV PAULISTA, 2150 - CERQUEIRA CESAR - SAO PAULO/SP - 01310-930': Latitude = -23.5577537, Longitude = -46.6601905
Coordinates for 'BANCO SOCIETE GENERALI  AVENIDA PAULISTA, 2300 - SÃO PAULO/ SP - 01310-300': Latitude = -23.5566043, Longitude = -46.66114229999999
Coordinates for 'BANCO SOFISA AL SANTOS, N 1496 - JARDIM PAULISTA - SAO PAULO/SP - 01418-100': Latitude = -23.563094, Longitude = -46.656158
Coordinates for 'BAT BRASIL - SOUZA CRUZ AVENIDA REBOUCAS, 10145 - PINHEIROS - SAO PAULO/SP - 05401-150': Latitude = -23.5655782, Longitude = -46.6805658
Coordinates for 'BESNI  RUA 24 DE MAIO, 195': Latitude = -23.5437902, Longitude = -46.6403215
Coordinates for 'BIO BRANDS RUA BONNARD, N 980 - ALPHAVILLE - CENTRO INDUSTRIAL E EMPRESARIAL - BARUERI - SAO PAULO/SP - 06454-020': Latitude = -23.4768588, Longitude = -46.8662018
Coordinates for 'BIOFAST - OSASCO RUA ELOY CANDIDO LOPES, 381 - CENTRO - OSASCO/SP - 06010-130': Latitude = -23.5368764, Longitude = -46.775113
Coordinates for 'BOTICARIO ACADEMIA R OSCAR FREIRE, N 1375 - PINHEIROS - SAO PAULO/SP - 05409-010': Latitude = -23.5599963, Longitude = -46.672541
Coordinates for 'BRADESCO - LEOPOLDINA RUA DR SEIDEL, 425 VILA LEOPOLDINA - SAO PAULO/SP - 05315-000': Latitude = -23.5324776, Longitude = -46.7346326
Coordinates for 'BRADY SETON AV CECI, 238 - TAMBORE - BARUERI - SP    ': Latitude = -23.4975325, Longitude = -46.8276181
Coordinates for 'CAIXA VIDA E PREVIDENCIA - BARUERI ALAMEDA ARAGUAIA, N 2104 - 23 ANDAR - ALPHAVILLE - BARUERI/SP - 06455-000': Latitude = -23.5012563, Longitude = -46.8412544
Coordinates for 'CAMPARI AL RIO NEGRO, 585 - ALPHAVILLE - BARUERI/SP - 06454-000': Latitude = -23.5004973, Longitude = -46.8486757
Coordinates for 'CDB - ANA ROSA AVENIDA CONSELHEIRO RODRIGUES ALVES, 300 - VILA MARIANA - SP': Latitude = -23.5829877, Longitude = -46.6413286
Coordinates for 'CENTRO UNIVERSITARIO FEI RUA TAMANDARE, N 688, LIBERDADE - LIBERDADE - SAO PAULO/SP - 06460-000': Latitude = -23.5646089, Longitude = -46.63570010000001
Coordinates for 'CHIESI FARMACEUTICA R DR GIACOMO CHIESI, N 151- KM 39,2 - ESTR ROMEIROS - VOTUPARIM - SANTANA DE PARNAIBA/SP - 06513-005': Latitude = -23.453917, Longitude = -46.916146
Coordinates for 'CIDADE II MÊTRO RUA BOA VISTA, 175 - CENTRO': Latitude = -23.5461736, Longitude = -46.6336507
Coordinates for 'CLEARTECH ALAMEDA RIO NEGRO, N 585 - ALPHAVILLE - BARUERI/SP - 06454-000': Latitude = -23.5003444, Longitude = -46.8483483
Coordinates for 'CLINICA FARES OSASCO AV ANTONIO AGU, 630 - CENTRO OSASCO CEP 06093-006': Latitude = -23.5329915, Longitude = -46.7790446
Coordinates for 'CONDOMINIO EPVL RUA MAJOR DE PALADINO, N 128 - VILA RIBEIRO DE BARROS - SÃO PAULO/SP - 05307-000': Latitude = -23.5227249, Longitude = -46.740067
Coordinates for 'CONDOMINIO LONG STAY BELA CINTRA RUA BELA CINTRA, N 521 - CERQUEIRA CESAR - SAO PAULO/SP - 03021-020': Latitude = -23.5533271, Longitude = -46.6573341
Coordinates for 'CROWE RUA QUINZE DE NOVEMBRO, 184 ANDAR - CENTRO , SAO PAULO/SP - 01013000': Latitude = -23.5472962, Longitude = -46.6340449
Coordinates for 'CRUZEIRO DO SUL - LIBERDADE RUA GALVAO BUENO, 868 - LIBERDADE - SAO PAULO/SP - 01506-000': Latitude = -23.5631017, Longitude = -46.6351446
Coordinates for 'CRUZEIRO DO SUL - PAULISTA AV PAULISTA, 1415 - BELA VISTA - SAO PAULO/SP - 01311-925': Latitude = -23.5628312, Longitude = -46.6552963
Coordinates for 'CRUZEIRO DO SUL - VILA LOBOS AV IMPERATRIZ LEOPOLDINA, 550 - VILA LEOPOLDINA - SAO PAULO/SP - 05305-000': Latitude = -23.5280885, Longitude = -46.7342225
Coordinates for 'CUSHMAN - ERICSSON ALAMEDA ARAGUAIA, 2104 - EDCEA CORPORATE - TORRE1 - 15 ANDAR - REFEITORIO - ALPHAVILLE INDUSTRIAL - BARUERI/SP - 06455-000': Latitude = -23.5012563, Longitude = -46.8412544
Coordinates for 'CYRELA PAULISTA AVENIDA PAULISTA, N 1063 - JARDIM PAULISTA - SAO PAULO/SP': Latitude = -23.5651874, Longitude = -46.652893
Coordinates for 'DASA - H9J AV CAUAXI, 64/118 - ALPHAVILLE - BARUERI/SP - 06454-020': Latitude = -23.49421, Longitude = -46.85326999999999
Coordinates for 'DASA - LV-VILA LEOPOLDINA AV IMPERATRIZ LEOPOLDINA, 1554 - VILA LEOPOLDINA - SAO PAULO/SP - 05305-002': Latitude = -23.534482, Longitude = -46.7278117
Coordinates for 'DASA CECI AV CECI, 426 TAMBORE - BARUERI/SP - 06460-120': Latitude = -23.4975989, Longitude = -46.8272306
Coordinates for 'DASA LIBERDADE GALVAO BUENO, N 257 - LIBERDADE - SAO PAULO/SP - 01506-000': Latitude = -23.5578957, Longitude = -46.6350059
Coordinates for 'DASA TAMBORÉ AV TAMBAQUI, 113 - TAMBORÉ': Latitude = -23.4982841, Longitude = -46.8383184
Coordinates for 'DELBONI - AUGUSTA RUA AUGUSTA, 1828 - JARDIM PAULISTA - SP': Latitude = -23.5586716, Longitude = -46.6609718
Coordinates for 'DELBONI JURUA AV JURUA, 434  - ALPHAVILLE INDUSTRIAL - BARUERI - SP': Latitude = -23.4998377, Longitude = -46.8559462
Coordinates for 'DEXCO SA AVENIDA PAULISTA, N 1938 - BELA VISTA - SAO PAULO/SP - 01310-942': Latitude = -23.5592102, Longitude = -46.6585195
Coordinates for 'DIGIO ALAMEDA XINGU, N 512 - ALPHAVILLE - BARUERI/SP - 06455-030': Latitude = -23.504675, Longitude = -46.8510115
Coordinates for 'DURATEX - DECA RUA COMENDADOR SOUSA, N 135 - AGUA BRANCA - SAO PAULO/SP - 05037-090': Latitude = -23.5182285, Longitude = -46.6879998
Coordinates for 'ECAD SP AV PAULISTA, N 171 - PARAISO - SAO PAULO/SP': Latitude = -23.570328, Longitude = -46.646204
Coordinates for 'EINSTEIN VILA MARIANA  R CORONEL LISBOA, 139 - VL MARIANA - SAO PAULO/SP - 04020-040': Latitude = -23.592096, Longitude = -46.63918839999999
Coordinates for 'ELOPAR ALAMEDA XINGU, N 512 - ALPHAVILLE - BARUERI/SP - 06455-030': Latitude = -23.5046199, Longitude = -46.8512449
Coordinates for 'EMBRATEL - INGLESES R DOS INGLESES, 600 - MORRO DOS INGLESES - SAO PAULO/SP - 01329-904': Latitude = -23.5635453, Longitude = -46.6465812
Coordinates for 'EMBRATEL - LAPA R ALDO DE AZEVEDO, 200 - LAPA - SAO PAULO/SP - 05453-030': Latitude = -23.5423855, Longitude = -46.7096696
Coordinates for 'EUROP ASSISTENCE AVENIDA JURUA, 320 - BARUERI/SP': Latitude = -23.4998188, Longitude = -46.8543777
Coordinates for 'FACULDADE SAO LEOPOLDO MANDIC RUA ITAPEVA, 538 - BELA VISTA - SAO PAULO/SP - 01332-020': Latitude = -23.5605966, Longitude = -46.6538184
Coordinates for 'FDE AV SAO LUIS, N 99 - REPUBLICA - SAO PAULO/SP - 01046-001': Latitude = -23.5456261, Longitude = -46.6429526
Coordinates for 'FGV RUA DOUTOR PLINIO BARRETO, 365 - BELA VISTA - SAO PAULO/SP': Latitude = -23.5581808, Longitude = -46.6526283
Coordinates for 'FIRST DATA - PAULISTA AV PAULISTA, N 2300 - BELA VISTA SAO PAULO/SP': Latitude = -23.556905, Longitude = -46.6615069
Coordinates for 'FLORA ALAMEDA ARAGUAIA, 211 - ALPHAVILLE INDUSTRIAL - BARUERI/SP - 06455-000': Latitude = -23.4986764, Longitude = -46.85931249999999
Coordinates for 'FLORA - AUTO PEÇAS AVENIDA FLORA, N 65 - JAGUARIBE - OSASCO/SP - 06053-040': Latitude = -23.5557245, Longitude = -46.7870242
Coordinates for 'FLORA TAMBORE ALAMEDA ARAGUAIA, N 3600 - ALPHAVILLE - BARUERI/SP - 06455-000': Latitude = -23.5039466, Longitude = -46.827678
Coordinates for 'FRESENIUS AV MARGINAL PROJETADA , 1652': Latitude = -23.5067194, Longitude = -46.8249953
Coordinates for 'GE BAND AVENIDA EMBAIXADOR MACEDO SOARES, 10001 - VL ANASTACIO - SÃO PAULO/SP - 05035-035': Latitude = -23.5100907, Longitude = -46.7107561
Coordinates for 'GE HEALTHCARE AV MARCOS PENTEADO DE ULHOA RODRIGUES, 690 - BARUERI/SP - 06460-040': Latitude = -23.5046212, Longitude = -46.8399674
Coordinates for 'GLOBO ALAMEDA SANTOS  ALAMEDA SANTOS,700': Latitude = -23.5679454, Longitude = -46.6506382
Coordinates for 'GO OFFICES LATAM AVENIDA PAULISTA, N 475 - CERQUEIRA CESAR - SAO PAULO/SP - 04039-004': Latitude = -23.5685827, Longitude = -46.6482924
Coordinates for 'GRANCOFFEE FILIAL SP RUA MAJOR PALADINO,128 - GALPAO 4 - VILA LEOPOLDINA - SAO PAULO/SP': Latitude = -23.5225355, Longitude = -46.7370364
Coordinates for 'HARALD FABRICA ESTR ANA PROCOPIO DE MORAES, 745 - VARZEA DE SOUZA - SANTANA DE PARNAIBA': Latitude = -23.4026122, Longitude = -46.8957638
Coordinates for 'HARALD MATRIZ RUA MUNDO, 378 JARDIM SILVIO - SANTANA DE PARNAÍBA - SP - CEP: 05528-451': Latitude = -23.4029554, Longitude = -46.8970491
Coordinates for 'HEINEKEN - CDA OSASCO R HENRY FORD, N 803 - PRESIDENTE ALTINO - OSASCO/SP': Latitude = -23.5274218, Longitude = -46.7625796
Coordinates for 'GREEN4T - BARUERI AV GUPE, N 10767 - JARDIM BELVAL - BARUERI/SP - 06422-120': Latitude = -23.5091426, Longitude = -46.9045369
Coordinates for 'HOSPITAL ALBERT EINSTEIN - ARTHUR DE AZEVEDO RUA ARTHUR DE AZEVEDO, N 411 - PINHEIROS - SAO PAULO/SP - 05404010': Latitude = -23.559578, Longitude = -46.6762406
Coordinates for 'HOSPITAL SAHA RUA MAESTRO CARDIM, 407': Latitude = -23.56485, Longitude = -46.6411417
Coordinates for 'HYPERMARCAS COSMED AV CECI, 282 - CENTRO EMPR TAMBORE - BARUERI/SP - 06460-120': Latitude = -23.4975989, Longitude = -46.8272306
Coordinates for 'HYPERMARCAS HYNOVA AV ANDROMEDA, 2000 - ALPHAVILLE EMP - BARUERI/SP - 05676-120': Latitude = -23.4853628, Longitude = -46.8694293
Coordinates for 'ICESP OSASCO R BENEDITO AMERICO DE OLIVEIRA,122 - VILA YARA - OSASCO - SP 06028-080': Latitude = -23.5471266, Longitude = -46.7650166
Coordinates for 'INDORAMA - OXITENO ALAMEDA SANTOS, N 960 - CERQUEIRA CESAR - SAO PAULO/SP': Latitude = -23.5661386, Longitude = -46.6517175
Coordinates for 'INOVA SAUDE SAO PAULO AVENIDA RIO BRANCO, N 1114 - CAMPOS ELISEOS - SAO PAULO/SP - 01206-001': Latitude = -23.5342087, Longitude = -46.6438757
Coordinates for 'INSTITUTO PHORTE DE EDUCACAO RUA TREZE DE MAIO 681, BELA VISTA - SAO PAULO/SP - 01327-000': Latitude = -23.5591842, Longitude = -46.64607540000001
Coordinates for 'INTERMÉDICA CARAPICUIBA AV TAMARA, 311 ANTIGO 60 - CARAPICUIBA - SP 06320-020': Latitude = -23.5226831, Longitude = -46.8375572
Coordinates for 'INTERMÉDICA ALPHAVILLE AL AMAZONAS, 329 - BARUERI - SP 06454-070': Latitude = -23.4971006, Longitude = -46.8445753
Coordinates for 'INTERMÉDICA LAPA RUA BATALHA DO PIRAJA, 157 - LAPA - SÃO PAULO - SP - 05065-120': Latitude = -23.5178575, Longitude = -46.69499889999999
Coordinates for 'INTERMÉDICA NOTRELABS POLVILHO AVENIDA TENENTE MARQUES, 1795 - PARAISO POLVILHO - CAJAMAR': Latitude = -23.410042, Longitude = -46.8392054
Coordinates for 'INTERMÉDICA OSASCO AV DOS AUTONOMISTAS 2502 - OSASCO - SP 06090-010': Latitude = -23.5375113, Longitude = -46.7768914
Coordinates for 'INTERMÉDICA PAULISTA  AV PAULISTA, 777': Latitude = -23.5667413, Longitude = -46.6506418
Coordinates for 'IT WORKS ALAMEDA RIO NEGRO, N 585 - ALPHAVILLE - BARUERI/SP - 06454-000': Latitude = -23.5003738, Longitude = -46.8497845
Coordinates for 'ITAU - AV PAULISTA AV PAULISTA, N 1374 - BELA VISTA - SAO PAULO/SP - 01310-100': Latitude = -23.5627603, Longitude = -46.65454039999999
Coordinates for 'ITAU BARUERI ( SO LEITURA) AL TOCANTINS 125 28 ANDAR ALPHAVILLE': Latitude = -23.5033622, Longitude = -46.8493551
Coordinates for 'ITAÚ UNIBANCO - AFACI - SP  PRACA PADRE MANOEL DA NOBREGA, 21 - SAO PAULO/SP - 01015-010': Latitude = -23.5479858, Longitude = -46.6338021
Coordinates for 'ITAUSA  AV PAULISTA, 1938 - BELA VISTA - SAO PAULO/SP - 01310200': Latitude = -23.559205, Longitude = -46.658537
Coordinates for 'KERRY - BARUERI ALAMEDA ARAPOEMA, 480 - TAMBORE, BARUERI/SP - 06460080': Latitude = -23.5013049, Longitude = -46.8267563
Coordinates for 'KOVI AV RAIMUNDO PEREIRA DE MAGALHAES, N 136 - VILA ANASTACIO - SAO PAULO/SP - 05092-040': Latitude = -23.5192139, Longitude = -46.7117456
Coordinates for 'LAVOISIER ALPHAVILLE ALAMEDA RIO NEGRO, 967 - ALPHAVILLE INDUSTRIAL, BARUERI - SP, 06454-000 ': Latitude = -23.4974032, Longitude = -46.8489491
Coordinates for 'LAVOISIER LAPA1 R TOME DE SOUZA, 197 - LAPA - SAO PAULO/SP - 05079000': Latitude = -23.5260299, Longitude = -46.70828960000001
Coordinates for 'LAVOISIER LAPA2 R TOME DE SOUZA, 220 - LAPA - SAO PAULO/SP - 05079000': Latitude = -23.5260299, Longitude = -46.70828960000001
Coordinates for 'LAVOISIER QUITAÚNA RUA JEQUIE 98 -QUITAÚNA': Latitude = -23.5261425, Longitude = -46.8105761
Coordinates for 'LAVOISIER REPUBLICA AV DR VIEIRA DE CARVALHO, N 176 - REPUBLICA - SAO PAULO/SP - 01210-010': Latitude = -23.5413112, Longitude = -46.6440352
Coordinates for 'LAVOISIER SHOPUNIÃO AV DOS AUTONOMISTAS, 1400 - VILA YARA - OSASCO - SP - 06020010': Latitude = -23.5414394, Longitude = -46.7660126
Coordinates for 'LEFORTE LIBERDADE  R GALVAO BUENO, 257 / 290 / 412- 1 ANDAR - LIBERDADE - SAO PAULO/SP': Latitude = -23.5578957, Longitude = -46.6350059
Coordinates for 'LELLO OSCAR FREIRE RUA OSCAR FREIRE, 667 - JARDIM PAULISTA - SAO PAULO/SP - 01426-003': Latitude = -23.5645796, Longitude = -46.6674414
Coordinates for 'LELLO PAULISTA AV PAULISTA, 302': Latitude = -23.5688619, Longitude = -46.6464484
Coordinates for 'LIVELO ALAMEDA XINGU, N 512 - ALPHAVILLE - BARUERI/SP - 06455-030': Latitude = -23.504641, Longitude = -46.851135
Coordinates for 'LOCALIZA - PAULISTA ALAMEDA SANTOS, N 1826 - JARDIM PAULISTA - SAO PAULO/SP - 01418-102': Latitude = -23.5611413, Longitude = -46.6585811
Coordinates for 'LOG FRIO LOGISTICA RUA JUSSARA, 1635 - SALA L - CAMARA 1 - JARDIM SANTA CECILIA - BARUERI/SP - 06465-070': Latitude = -23.5106118, Longitude = -46.8190936
Coordinates for 'LOGICALIS - BARUERI AV TAMBORE, N 267 - BARUERI/SP - 06460-000': Latitude = -23.5037035, Longitude = -46.8444721
Coordinates for 'LOGICALIS - WESERVICE AV TAMBORE, N 267 - BARUERI/SP - 06460-000': Latitude = -23.5037035, Longitude = -46.8444721
Coordinates for 'MATCHEM - SANTANA DE PARNAIBA RUA SAO PAULO, N 92 - JARDIM VARZEA - SANTANA DE PARNAIBA': Latitude = -23.406855, Longitude = -46.8735113
Coordinates for 'METRICS AVENIDA PAULISTA, 302 - 12 ANDAR SALA 82 - BELA VISTA - SAO PAULO/SP - 01310-000': Latitude = -23.5692399, Longitude = -46.6465328
Coordinates for 'METRO CCO  RUA VERGUEIRO, 1200 - LIBERDADE - SAO PAULO/SP - 01504-000': Latitude = -23.5728094, Longitude = -46.6403599
Coordinates for 'MELHORAMENTOS LAPA R TITO, 479 - LAPA - SAO PAULO - SP 05051-000': Latitude = -23.5282751, Longitude = -46.69637849999999
Coordinates for 'METTLER AVENIDA TAMBORE, 418 - TAMBORE - BARUERI/SP - 06460-000': Latitude = -23.5024184, Longitude = -46.8428163
Coordinates for 'MINERACAO TABOCA ALAMEDA RIO NEGRO 161, 5 ANDAR': Latitude = -23.5039187, Longitude = -46.8482573
Coordinates for 'MITRE HEALTHY ALAMEDA SANTOS, N 700 - CERQUEIRA CESAR/SP - 01418-002': Latitude = -23.5593967, Longitude = -46.6687592
Coordinates for 'ML GOMES SAO PAULO RUA 15 DE NOVEMBRO, N 137 - CENTRO - SAO PAULO/SP - 01013-000': Latitude = -23.5480147, Longitude = -46.634128
Coordinates for 'NEOBPO  AVENIDA IPIRANGA, 855 - CENTRO - SP': Latitude = -23.5420433, Longitude = -46.6403968
Coordinates for 'NEOBPO SÃO JOAO RUA CONSELHEIRO DE NEBIAS, 14': Latitude = -23.5418875, Longitude = -46.6406807
Coordinates for 'NOKIA RUA WERNER VON SIEMENS, 111 - PREDIO 25  BLOBO C  1 ANDAR E - BUSINESS - LAPA': Latitude = -23.5108448, Longitude = -46.7109888
Coordinates for 'NOTRELAB INTERMÉDICA - OSASCO AV:AVENIDA DOS AUTONOMISTAS 2515': Latitude = -23.5378496, Longitude = -46.7771172
Coordinates for 'NOTRELABS UNIDADE ITABUNA R ITABUNA, N 76 - CENTRO - OSASCO/SP': Latitude = -23.5371653, Longitude = -46.7752926
Coordinates for 'NUBANK AVENIDA JOSE CESAR DE OLIVEIRA, 21 - VILA LEOPOLDINA - SAO PAULO/SP - 05317-000': Latitude = -23.5413032, Longitude = -46.731322
Coordinates for 'ODONTOPREV ALAMEDA ARAGUAIA, 2104 - 20 ANDAR - CENTRO EMPRESARIAL ALPHAVILLE - ALPHAVILE - BARUERI/SP - 06455-000': Latitude = -23.5012563, Longitude = -46.8412544

In [18]:
large_office_handover

,FILIAL,CONTRATO,PARCEIRO,PATRIMÔNIO,"PATRIMONIO sem ""0""",MODELO,CAPACIDADE EM DOSES,TIPO DE MAQUINA,PDV,CLIENTE,...,Sex,Sáb,Dom,Frequência Atual,CLIENTE AJUSTADO,ENDEREÇO AJUSTADO,PATRIMÔNIOS AJUSTADA,KEY CLIENTE ENDEREÇO,Latitude2,Longitude2
4,SP,35477.0,35614.0,028666,28666,MAQ VENDING BQ NW KREA ONE TOUCH,220,BEBIDAS QUENTES,10 ANDAR COPA,99 TAXIS,...,NaN,NaN,NaN,-,99 TAXIS,"AVENIDA PAULISTA, N 2537 - BELA VISTA - SAO PA...",28666,"99 TAXIS AVENIDA PAULISTA, N 2537 - BELA VISTA...",-23.556438,-46.662896
5,SP,35477.0,35614.0,033465,33465,MAQ VENDING BQ NW KREA ONE TOUCH,220,BEBIDAS QUENTES,7 ANDAR,99 TAXIS,...,NaN,NaN,NaN,-,99 TAXIS,"AVENIDA PAULISTA, N 2537 - BELA VISTA - SAO PA...",33465,"99 TAXIS AVENIDA PAULISTA, N 2537 - BELA VISTA...",-23.556438,-46.662896
6,SP,35477.0,35614.0,28501,28501,MAQ VENDING BQ NW KREA ONE TOUCH,220,BEBIDAS QUENTES,7 ANDAR,99 TAXIS,...,X,NaN,NaN,5,99 TAXIS,"AVENIDA PAULISTA, N 2537 - BELA VISTA - SAO PA...",28501,"99 TAXIS AVENIDA PAULISTA, N 2537 - BELA VISTA...",-23.556438,-46.662896
7,SP,43179.0,35614.0,034757,34757,MAQ VENDING BQ NW KREA ONE TOUCH,220,BEBIDAS QUENTES,NaN,99 TAXIS,...,NaN,NaN,NaN,-,99 TAXIS,"AVENIDA PAULISTA, N 2537 - BELA VISTA - SAO PA...",34757,"99 TAXIS AVENIDA PAULISTA, N 2537 - BELA VISTA...",-23.556438,-46.662896
8,SP,35477.0,35614.0,030933,30933,MAQ VENDING BQ NW KREA,220,BEBIDAS QUENTES,5 ANDAR,99 TAXIS,...,X,NaN,NaN,5,99 TAXIS,"AVENIDA PAULISTA, N 2537 - BELA VISTA - SAO PA...",30933,"99 TAXIS AVENIDA PAULISTA, N 2537 - BELA VISTA...",-23.556438,-46.662896
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3459,SP,2922.0,75.0,8182,8182,MAQ VENDING BQ BIANCHI LEI 400,400,BEBIDAS QUENTES,BLOCO B 8° ANDAR,VIVO HUMBERTO,...,NaN,NaN,NaN,-,VIVO HUMBERTO,"R HUMBERTO I, 880 - VILA MARIANA, SÃO PAULO -...",8182,"VIVO HUMBERTO R HUMBERTO I, 880 - VILA MARIA...",-23.587739,-46.640658
3460,SP,2922.0,75.0,8169,8169,MAQ VENDING BQ BIANCHI LEI 400,400,BEBIDAS QUENTES,BLOCO B 7° ANDAR,VIVO HUMBERTO,...,NaN,NaN,NaN,-,VIVO HUMBERTO,"R HUMBERTO I, 880 - VILA MARIANA, SÃO PAULO -...",8169,"VIVO HUMBERTO R HUMBERTO I, 880 - VILA MARIA...",-23.587739,-46.640658
3462,SP,2922.0,75.0,8262,8262,MAQ VENDING BQ BIANCHI BVM 921,200,BEBIDAS QUENTES,RECEPCAO,VIVO OSASCO,...,NaN,NaN,NaN,2,VIVO OSASCO,"RUA ALBINO DOS SANTOS, 175 - CENTRO - OSASCO/S...",8262,"VIVO OSASCO RUA ALBINO DOS SANTOS, 175 - CENTR...",-23.530999,-46.785398
3498,SP,41600.0,1019195.0,13518,13518,MAQ VENDING BQ BIANCHI LEI 400,400,BEBIDAS QUENTES,1 ANDAR BLOCO B,VOTORANTIM - LEOPOLDINA,...,X,NaN,NaN,5,VOTORANTIM - LEOPOLDINA,"AV MANUEL BANDEIRA, N 291 - BLOCO B 1 ANDAR - ...",13518,"VOTORANTIM - LEOPOLDINA AV MANUEL BANDEIRA, N...",-23.541408,-46.733697
3542,SP,37939.0,485163.0,033466,33466,MAQ VENDING BQ NW KREA,220,BEBIDAS QUENTES,1 ANDAR - COPA,WIPRO ALPHAVILLE,...,X,NaN,NaN,5,WIPRO ALPHAVILLE,"AL RIO NEGRO, 585 - ALPHAVILLE INDUSTRIAL - BA...",33466,"WIPRO ALPHAVILLE AL RIO NEGRO, 585 - ALPHAVILL...",-23.500753,-46.848970

In [23]:
large_office_handover.loc[large_office_handover['Latitude2'].isna()]['CLIENTE'].unique()

array([], dtype=object)

In [27]:
for cliente in large_office_handover['CLIENTE AJUSTADO'].unique():
    end_por_cliente = large_office_handover.loc[(large_office_handover['CLIENTE AJUSTADO'] == cliente)]['ENDEREÇO AJUSTADO'].unique()
    for i in range(0, len(end_por_cliente)):
        large_office_handover.loc[((large_office_handover['CLIENTE AJUSTADO'] == cliente) &
                (large_office_handover['ENDEREÇO AJUSTADO'] == end_por_cliente[i])), 'CLIENTE AJUSTADO ÚNICO 2'] = cliente + " " + str(i)

C:\Users\tbekho01.ATKEARNEY_AD\AppData\Local\Temp\ipykernel_10940\3512460857.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  large_office_handover.loc[((large_office_handover['CLIENTE AJUSTADO'] == cliente) &

In [28]:
large_office_handover

,FILIAL,CONTRATO,PARCEIRO,PATRIMÔNIO,"PATRIMONIO sem ""0""",MODELO,CAPACIDADE EM DOSES,TIPO DE MAQUINA,PDV,CLIENTE,...,Sáb,Dom,Frequência Atual,CLIENTE AJUSTADO,ENDEREÇO AJUSTADO,PATRIMÔNIOS AJUSTADA,KEY CLIENTE ENDEREÇO,Latitude2,Longitude2,CLIENTE AJUSTADO ÚNICO 2
4,SP,35477.0,35614.0,028666,28666,MAQ VENDING BQ NW KREA ONE TOUCH,220,BEBIDAS QUENTES,10 ANDAR COPA,99 TAXIS,...,NaN,NaN,-,99 TAXIS,"AVENIDA PAULISTA, N 2537 - BELA VISTA - SAO PA...",28666,"99 TAXIS AVENIDA PAULISTA, N 2537 - BELA VISTA...",-23.556438,-46.662896,99 TAXIS 0
5,SP,35477.0,35614.0,033465,33465,MAQ VENDING BQ NW KREA ONE TOUCH,220,BEBIDAS QUENTES,7 ANDAR,99 TAXIS,...,NaN,NaN,-,99 TAXIS,"AVENIDA PAULISTA, N 2537 - BELA VISTA - SAO PA...",33465,"99 TAXIS AVENIDA PAULISTA, N 2537 - BELA VISTA...",-23.556438,-46.662896,99 TAXIS 0
6,SP,35477.0,35614.0,28501,28501,MAQ VENDING BQ NW KREA ONE TOUCH,220,BEBIDAS QUENTES,7 ANDAR,99 TAXIS,...,NaN,NaN,5,99 TAXIS,"AVENIDA PAULISTA, N 2537 - BELA VISTA - SAO PA...",28501,"99 TAXIS AVENIDA PAULISTA, N 2537 - BELA VISTA...",-23.556438,-46.662896,99 TAXIS 0
7,SP,43179.0,35614.0,034757,34757,MAQ VENDING BQ NW KREA ONE TOUCH,220,BEBIDAS QUENTES,NaN,99 TAXIS,...,NaN,NaN,-,99 TAXIS,"AVENIDA PAULISTA, N 2537 - BELA VISTA - SAO PA...",34757,"99 TAXIS AVENIDA PAULISTA, N 2537 - BELA VISTA...",-23.556438,-46.662896,99 TAXIS 0
8,SP,35477.0,35614.0,030933,30933,MAQ VENDING BQ NW KREA,220,BEBIDAS QUENTES,5 ANDAR,99 TAXIS,...,NaN,NaN,5,99 TAXIS,"AVENIDA PAULISTA, N 2537 - BELA VISTA - SAO PA...",30933,"99 TAXIS AVENIDA PAULISTA, N 2537 - BELA VISTA...",-23.556438,-46.662896,99 TAXIS 0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3459,SP,2922.0,75.0,8182,8182,MAQ VENDING BQ BIANCHI LEI 400,400,BEBIDAS QUENTES,BLOCO B 8° ANDAR,VIVO HUMBERTO,...,NaN,NaN,-,VIVO HUMBERTO,"R HUMBERTO I, 880 - VILA MARIANA, SÃO PAULO -...",8182,"VIVO HUMBERTO R HUMBERTO I, 880 - VILA MARIA...",-23.587739,-46.640658,VIVO HUMBERTO 0
3460,SP,2922.0,75.0,8169,8169,MAQ VENDING BQ BIANCHI LEI 400,400,BEBIDAS QUENTES,BLOCO B 7° ANDAR,VIVO HUMBERTO,...,NaN,NaN,-,VIVO HUMBERTO,"R HUMBERTO I, 880 - VILA MARIANA, SÃO PAULO -...",8169,"VIVO HUMBERTO R HUMBERTO I, 880 - VILA MARIA...",-23.587739,-46.640658,VIVO HUMBERTO 0
3462,SP,2922.0,75.0,8262,8262,MAQ VENDING BQ BIANCHI BVM 921,200,BEBIDAS QUENTES,RECEPCAO,VIVO OSASCO,...,NaN,NaN,2,VIVO OSASCO,"RUA ALBINO DOS SANTOS, 175 - CENTRO - OSASCO/S...",8262,"VIVO OSASCO RUA ALBINO DOS SANTOS, 175 - CENTR...",-23.530999,-46.785398,VIVO OSASCO 0
3498,SP,41600.0,1019195.0,13518,13518,MAQ VENDING BQ BIANCHI LEI 400,400,BEBIDAS QUENTES,1 ANDAR BLOCO B,VOTORANTIM - LEOPOLDINA,...,NaN,NaN,5,VOTORANTIM - LEOPOLDINA,"AV MANUEL BANDEIRA, N 291 - BLOCO B 1 ANDAR - ...",13518,"VOTORANTIM - LEOPOLDINA AV MANUEL BANDEIRA, N...",-23.541408,-46.733697,VOTORANTIM - LEOPOLDINA 0
3542,SP,37939.0,485163.0,033466,33466,MAQ VENDING BQ NW KREA,220,BEBIDAS QUENTES,1 ANDAR - COPA,WIPRO ALPHAVILLE,...,NaN,NaN,5,WIPRO ALPHAVILLE,"AL RIO NEGRO, 585 - ALPHAVILLE INDUSTRIAL - BA...",33466,"WIPRO ALPHAVILLE AL RIO NEGRO, 585 - ALPHAVILL...",-23.500753,-46.848970,WIPRO ALPHAVILLE 0

In [33]:
path = r"C:\Users\tbekho01.ATKEARNEY_AD\Kearney\Gran Coffee - Otimização de despesas operacionais - Project Management\5. Working Folder\24. Handover\250826_Otimização de Abastecedores_vEnviado\Dados Intermediários\Endereços_Alan_André.xlsx"

large_office_handover.to_excel(path, index=False)